#if 0

          !!! WARNING !!!
This is a generated file.  Do not manually edit.
To enable/disable optional components, please create a user.cfg file.
See the LIS Users' Guide for more informaion.

#endif
#define RM_RETROSPECTIVE
#define RM_AGRMETMODE
#define RM_WRF_COUPLING
#undef RM_GCE_COUPLING
#define RM_PARAM_ESTIMATION
#define RM_RTM_FORWARD
#define RM_ENSEMBLE_SMOOTHER
#define RM_FORECAST
#define MF_MET_TEMPLATE
#define MF_LDT_GENERATED
#define MF_CLIMATOLOGY
#undef MF_GENENSFCST
#undef MF_PPTENSFCST
#define MF_GDAS
#undef MF_GDAS_T1534
#undef MF_GEOS
#undef MF_GEOS5_FORECAST
#define MF_GEFS_FORECAST
#undef MF_ECMWF
#undef MF_GSWP1
#undef MF_GSWP2
#undef MF_ECMWF_REANALYSIS
#undef MF_AGRMET
#define MF_PRINCETON
#undef MF_NLDAS1
#define MF_NLDAS2
#undef MF_GLDAS
#undef MF_GFS
#undef MF_MERRA_LAND
#define MF_MERRA2
#define MF_ERA5
#undef MF_CMAP
#undef MF_CHIRPS2
#undef MF_TRMM_3B42RT
#undef MF_TRMM_3B42RTV7
#undef MF_TRMM_3B42V6
#undef MF_TRMM_3B42V7
#undef MF_CPC_CMORPH
#define MF_GPM_IMERG
#undef MF_CPC_STAGEII
#undef MF_CPC_STAGEIV
#undef MF_NARR
#undef MF_ALMIPII
#undef MF_RFE2_DAILY
#undef MF_CEOP
#undef MF_SCAN
#undef MF_ARMS
#undef MF_GDAS_LSWG
#undef MF_RDHM_3_5_6
#undef MF_GDAS_3D
#undef MF_AGRMET_RADIATION_POLAR_STEREOGRAPHIC
#undef MF_AGRMET_RADIATION_LATLON
#define MF_BONDVILLE
#undef MF_FASST_TEST
#undef MF_TRIGRS_TEST
#undef MF_SNOTEL
#undef MF_COOP
#undef MF_RHONE_AGG
#undef MF_RFE2_GDAS_BIAS_CORRECTED
#undef MF_VIC_PROCESSED_FORCING
#undef MF_PALS_STATION_FORCING
#undef MF_PILDAS
#undef MF_PET_USGS
#undef MF_CAPA
#undef MF_NAM242
#undef MF_WRFOUT
#undef MF_AWAP
#undef MF_HIMAT_GMU
#undef MF_LOOBOS
#define MF_MRMS
#define PARAM_MODIS_REAL_TIME
#define PARAM_ALMIPII_LAI
#define PARAM_NESDIS_WEEKLY
#define PARAM_SPORT
#define PARAM_VIIRS
#define PARAM_ALMIPII_GFRAC
#define PARAM_ALMIPII_ROUGHNESS
#define PARAM_ALMIPII_ALBEDO
#define PARAM_ALMIPII_EMISSIVITY
#undef RTMS_CRTM
#define RTMS_CRTM2
#define RTMS_CRTM2EM
#define RTMS_CMEM
#define RTMS_TAU_OMEGA
#undef APP_GLS
#undef APP_TRIGRS
#undef ROUTE_NLDAS_ROUTER
#define ROUTE_HYMAP_ROUTER
#define ROUTE_HYMAP2_ROUTER
#define IRR_SPRINKLER
#define IRR_FLOOD
#define IRR_DRIP
#define DA_DIRECT_INSERTION
#define DA_ENKF
#define DA_ENSRF
#define DA_EKF
#define DA_ENKS
#define DA_PF
#define DA_OBS_SYNTHETICSM
#define DA_OBS_SYNTHETICWL
#define DA_OBS_SYNTHETICSND
#define DA_OBS_SYNTHETICSNOWTB
#define DA_OBS_SNODEP
#define DA_OBS_USAFSI
#define DA_OBS_PMW_SNOW
#define DA_OBS_ANSA_SCF
#undef DA_OBS_ESACCI_SM
#undef DA_OBS_LPRM_AMSRESM
#define DA_OBS_SMMR_SNWD
#define DA_OBS_SSMI_SNWD
#define DA_OBS_ANSA_SNWD
#define DA_OBS_GCOMW_AMSR2L3SND
#undef DA_OBS_SMOPS_ASCATSM
#undef DA_OBS_SMOPS_SMOSSM
#undef DA_OBS_SMOPS_AMSR2SM
#undef DA_OBS_SMOPS_SMAPSM
#undef DA_OBS_SMOS_NESDIS
#undef DA_OBS_NASA_SMAPSM
#define DA_OBS_NASA_SMAPVOD
#define DA_OBS_ASO_SWE
#define DA_OBS_GLASS_LAI
#define DA_OBS_GLASS_Albedo
#define DA_OBS_MODISSPORT_LAI
#undef DA_OBS_NRT_SMAPSM
#undef DA_OBS_PILDAS
#undef DA_OBS_GRACE
#define BE_bias_estimation
#define PERT_perturbations
#define OPTUE_ALG_ES
#define OPTUE_ALG_LM
#define OPTUE_ALG_GA
#define OPTUE_ALG_SCEUA
#define OPTUE_ALG_MCSIM
#define OPTUE_ALG_RWMCMC
#define OPTUE_ALG_DEMC
#define OPTUE_ALG_DEMCZ
#define PE_OBS_TEMPLATE
#define PE_OBS_PESYNSM1
#define PE_OBS_ISCCP_TSKIN
#define PE_OBS_WGPBMRSM
#define PE_OBS_CNRS
#define PE_OBS_AMSRE_SR
#define PE_OBS_LPRM_AMSRESM
#define PE_OBS_EMPTYOBS
#define PE_OBS_ARM
#define PE_OBS_MACON_LS_DATA
#define PE_OBS_GLOBAL_LS_DATA
#define PE_OBS_AMERIFLUX
#define PE_OBS_FLUXNET
#define PE_OBS_USDA_ARSSM
#define PE_OBS_ARSSM
#define PE_OBS_ISMNSM
#define PE_OBS_SMAPSM
#define PE_OBS_UASNOW
#define PE_OBJFUNC_LS
#define PE_OBJFUNC_LM
#define PE_OBJFUNC_LL
#define PE_OBJFUNC_P
#define SM_LSM_TEMPLATE
#undef SM_NOAH_2_7_1
#undef SM_NOAH_3_2
#undef SM_NOAH_3_3
#define SM_NOAH_3_6
#define SM_NOAH_3_9
#define SM_NOAHMP_3_6
#define SM_NOAHMP_4_0_1
#define SM_SNOWMODEL
#undef SM_RUC_3_7
#undef SM_CLM_2
#undef SM_VIC_4_1_1
#undef SM_VIC_4_1_2
#undef SM_MOSAIC
#undef SM_HYSSIB
#undef SM_JULES_4_3
#undef SM_JULES_5_0
#undef SM_JULES_5_1
#undef SM_JULES_5_2
#undef SM_JULES_5_3
#undef SM_JULES_5_4
#undef SM_JULES_5_X
#undef SM_CABLE
#undef SM_FASST
#undef SM_CLSM_F2_5
#undef SM_GEOWRSI_2
#undef SM_RDHM_3_5_6
#undef SM_SUMMA_1_0
#undef SM_FLAKE_1_0
#define SM_NOAHMP_GLACIER_3_9_1_1
#define SM_GLACIER_TEMPLATE
#define SM_TEMPLATE_OPEN_WATER
#undef FA_ESPBOOT
#undef FA_ESPCONV
